# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

tlsh_simple_hash_r <- function(v) {
    .Call('_tlsh_tlsh_simple_hash_r', PACKAGE = 'tlsh', v)
}

tlsh_simple_hash_c <- function(v) {
    .Call('_tlsh_tlsh_simple_hash_c', PACKAGE = 'tlsh', v)
}

tlsh_diff_fingerprints <- function(hash1, hash2) {
    .Call('_tlsh_tlsh_diff_fingerprints', PACKAGE = 'tlsh', hash1, hash2)
}

